defaults: &defaults
  rsync_server: rsync.lax.edgecastcdn.net
  user:         thibaud@jilion.com
  password:     LmUJXuj7TR7jnHw3vEf38WZJwGW7VaF3EPMh

development:
  <<: *defaults
  logs_path: '/test/logs'

test:
  <<: *defaults
  logs_path: '/test/logs'

production:
  <<: *defaults
  logs_path: '/logs'
